# Generated by Django 4.0.6 on 2022-07-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('prn', models.TextField(blank=True, null=True, unique=True)),
                ('date', models.TextField(blank=True, null=True)),
                ('bed_no', models.TextField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
